paths:
  #------- Ruta para obtener todos los productos -----------
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        200:
          description: The list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          description: Internal server error 
  #------- Ruta para obtener un producto por id --------------
  /api/products/{id}:
    get:
      tags:
        - Products
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          description: ID unique of the product
          required: true
          schema:
            type: string
      responses:
        200:
          description: The product was obtained correctly
        404:
          description: The product was not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              

#------ cuerpo del producto como ejemplo -------------
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id generated by data base mongoose
        title:
          type: string
          description: Title of the product
        description:
          type: string
          description: Description of the product
        price:
          type: number
          description: Price of the product
        code:
          type: string
          description: Code of the product alphanumeric
        stock:
          type: number
          description: Stock of the product
        category:
          type: string
          description: Category of the product
        thumbnail:
          type: array
          items:
            type: string
          description: Thumbnail of the product
        owner:
          type: ObjectId
          description: Owner of the product, default is admin
      
      example:
        _id: ObjectId("62b8a7b4b8a7b4b8a7b4b8a7")
        title: Bombis Maria
        description:  Prenda 100% algodon
        price: 10000
        code: ADC125
        stock: 10
        category: Bombis
        thumbnail: []
        owner: ObjectId("876a7b4b8a7b4b8a7b4b8a7b")


