paths:
  /api/products/:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        200:
          description: The list of products
        500:
          description: Internal server error 
          # content:
          #   application/json:
          #     schema:
          #       type: array
          #       items:
          #         $ref: '#/components/schemas/Product'